### ISSUE TITLE
【建议】多个地址代理和增加config文件

### ISSUE THREAD

**Issue by swRains** [zanjie1999/tcp-over-websocket#12]
如果可以同时添加多个代理，通过读取config文件来管理是不是会更好，比如tcp2ws -config.cfg
config文件里就一行一个代理，或者说定义一些.crt和.key文件的路径，我想这样会不会更好。每次重启都打这一长串........

**Comment by zanjie1999** [comment]
#2 
你可以写到开机启动，有想过，但目前是一个线程管一个转发，也没几个参数，为他增加一个配置文件实在是有点多余

**Comment by zanjie1999** [comment]
还是开起来吧，欢迎pr，有空的话我就写一下
另外想到了可以用bash或者service来实现这个需求

**Comment by swRains** [comment]
windows的bat我已经写了，linux的bash还得学习下，还是用的太少了

**Comment by zanjie1999** [comment]
举个例子
```
nohup tcp2ws路径 你的启动参数 > 日志文件 &
```
一行一个写到一个sh文件中，然后`chmod +x 文件名`，这样就能运行了 
```
nohup tcp2ws 22 62222 > server.log &
nohup tcp2ws ws://127.0.0.1:62222 6222 > client. log &
```
停止
```
killall tcp2ws
```

**Comment by swRains** [comment]
> 

谢谢，这几天我研究学习下，有几台虚拟机要藏一下ssh端口-.-

**Comment by HanadaLee** [comment]
我觉得这个需求挺好的，我现在就是用systemd或者docker拉起一个config.conf文件，这个文件本质上是一个shell文件，
```
#!/bin/bash

# client - xxxxx1
/usr/local/tcp2ws/bin/tcp2ws xxx xxxxx &
# client - xxxxx2
/usr/local/tcp2ws/bin/tcp2ws xxxx xxxx &
# Keep Script Running (if you use systemd to run this script, please remove it)
wait
```

tcp2ws.service
```
[Unit]
Description=TCP to WebSocket Proxy
After=network.target

[Service]
Type=forking
ExecStart=/usr/local/tcp2ws/etc/config.conf
ExecStop=/usr/local/tcp2ws/bin/tcp2ws
Restart=on-failure
StartLimitBurst=0

[Install]
WantedBy=multi-user.target
```

docker-compose.yml
```
version: "3"

services:
  tcp2ws:
    image: registry.internal.com/hanada/tcp2ws:11.1
    container_name: tcp2ws
    network_mode: host
    entrypoint: ["/bin/bash", "/usr/local/tcp2ws/etc/config.conf"] 
    restart: unless-stopped
    volumes:
      - ./etc/config.conf:/usr/local/tcp2ws/etc/config.conf
```
虽然但是，实现起来还是好奇怪，感觉像是奇技淫巧
我是建议如果不想搞多线程逻辑，其实可以一个master，自身不跑服务，只载入或更新配置文件，带多个worker进程，每个worker进程跑一个tcp2ws配置实例
